apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  selector:
    matchLabels:
      app: url-shortener
  replicas: 3
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: mysecret
        