version: "3.4"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  mongodb:
    image: mongo
  redis:
    image: redis